### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by unRob** [unRob/representantes.pati.to#1]
Amigos y colaboradores, @lalo me hizo pensar en la licencia del proyecto, y llevo rato pensando en como implementar algo con lo que me sienta cómodo. Les pido que revisen esta (que está muy inspirada en BSD), y me den su opinion al respecto, para que en caso de que les parezca apta, la implemente y pueda hacer el repo público.

---

Copyright (c) 2014, Partido Surrealista Mexicano
Todos los derechos reservados.

La redistribución y uso como código fuente y/u objeto, con o sin modificaciones, está permitida siempre y cuando todas las siguientes condiciones sean respetadas:
- La redistribución del código fuente debe mantener la nota de copyright antes mencionada, esta lista de condiciones y la renuncia de responsabilidades que acompaña esta licencia.
- La redistribución del código objeto debe mantener la nota de copyright antes mencionada, esta lista de condiciones y la renuncia de responsabilidades que acompaña esta licencia en la documentación y en cualquier otro material que se ofrezca con el código objeto.
- El nombre "Representantes Patito", ni el nombre de loas colaboradoreas originales podrá ser usado para promocionar o endosar productos derivados de este software sin un consentimiento previo por escrito de los mismos.
- Todo uso de este código fuente y archivos relacionados, en su conjunto o de manera individual, así como el material publicitario que mencione las funciones del mismo deberá incluir la leyenda: "Este producto incluye software desarrollado por el Partido Surrealista Mexicano y Colaboradoreas", así como un enlace a esta licencia, y deberá indicar si se han hecho cambios al mismo.
- Cualquier uso o implementación de este código fuente y archivos relacionados, en su conjunto o de manera individual, deberá extender los mismos derechos y obligaciones que menciona esta licencia.
- Se prohibe el uso de este código cuándo el uso mismo incite o resulte en la discriminación de cualquier individuo o grupo de individuos, en función de su género, orientación sexual, educación y/o poder adquisitivo.
- El uso de este código sugiere, más no exige, a los usuarioas del mismo a invitar al Partido Surrealista Mexicano y a cada uno de los Colaboradoreas unos mezcales ó bebidas no-alcoholicas de su elección, como muestra de compañerismo y buena voluntad.

Este software se ofrece por los titulares de derechos de autor y colaboradores "tal cual", y cualquier garantía explícita o implícita, por ejemplo, de manera enunciativa más no limitativa, la garantía implícita de comercialización y aptitud para un propósito determinado son rechazadas. Bajo ninguna circunstancia serán responsables los titulares de derechos de autor ni colaboradores por cualquier daño directo, indirecto, incidental, especial, ejemplar o consecuente —incluyendo, pero no limitado a, la adquisición de bienes o servicios; la pérdida uso, datos o beneficios; o interrupción de la actividad empresarial—, o por cualquier teoría de responsabilidad estricta ó agravio (incluyendo negligencia, o cualquier otra causa) que surja de la posibilidad de tales daños.

**Comment by unRob** [comment]
Por cierto, el uso ambiguo de géneros gramaticales es a propósito, cualquier otra falta de ortografía no.

**Comment by unRob** [comment]
Bueno, no veo mucha actividad, supongo que están de acuerdo :)

**Comment by lalo** [comment]
Te debemos unas cervezas al parecer. Yo le agregaría algo sobre el uso comercial (amenos que no lo quieras prohibir) y agregarle algo sobre de publicar los cambios electrónicamente como AGPL (solo sugerencia)

**Comment by unRob** [comment]
@lalo ¿Lo están usando? Qué chido!

No estoy tan seguro de querer limitar el uso comercial, pero lo de publicar cambios de manera electrónica es algo que creo que valdría mucho la pena, le voy a echar una leída. Gracias!

**Comment by unRob** [comment]
Quedaría algo como:

> - Cualquier uso o implementación de este código fuente y archivos relacionados, en su conjunto o de manera individual, deberá extender los mismos derechos y obligaciones que menciona esta licencia **, así como hacer disponibles públicamente las modificaciones al mismo, de existir, de manera electrónica**.

**Comment by lalo** [comment]
Suena bien
