### ISSUE TITLE
La búsqueda podría ser más sencilla con un input de búsqueda de dirección

### ISSUE THREAD

**Issue by xiam** [unRob/representantes.pati.to#2]
La para encontrar tu domicilio en http://representantes.pati.to/ es ubicar un pin. Lo que hace necesario que sepas navegar en un mapa de google: arrastrar, hacer zoom, etc. Todo sería más rápido con un input donde se pueda encontrar la dirección con autocompletado.

Referencia: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

Si la ven bien, podría tomar la tarea.

**Comment by unRob** [comment]
Estoy de acuerdo, pero sólo si no tienes un browser que aguante [`navigator.geolocation.getCurrentPosition`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation), o por alguna razón no quisieras usar la funcionalidad (privacidad, ¿supongo?).

Por otro lado, creo que implementar alguna librería de [geoIP](http://dev.maxmind.com/geoip/legacy/geolite/) podría ayudar en algunos casos, siempre y cuando la lista esté actualizada (para axtel, por ejemplo no jala muy bien).

**Comment by lalo** [comment]
:+1:, yo tengo desactivado lo de geoloc y lo uso arrastrando y con el zoom como menciona @xiam

**Comment by unRob** [comment]
Ya pensé bien en el cambio de uso, y más cuando Safari decide cagar su manera de leer prototipos en JS. Me parecería un buen feature, me voy a poner a hacer yo la parte de geoIP, esperando que ayude un poco también para los usuarios que así lo prefieran.
